[workspace]
resolver = "2"
members = [
    "core/malsim-core",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mal-lang/mal-simulator"
publish = false

[workspace.dependencies]
malsim-core = { path = "core/malsim-core" }

maltoolbox-attackgraph = { git = "https://github.com/mal-lang/mal-toolbox", rev = "c854d1d6567ecb8851cf52a340a3ec5b673467f4" }
maltoolbox-language = { git = "https://github.com/mal-lang/mal-toolbox", rev = "c854d1d6567ecb8851cf52a340a3ec5b673467f4" }
