[workspace]
resolver = "2"
members = [
    "malsim-pyo3",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
pyo3 = "0.29.3"

maltoolbox-attackgraph = { git = "https://github.com/mal-lang/mal-toolbox", rev = "b96258bad474282b975245d9848f7c25d195d508" }
maltoolbox-model = { git = "https://github.com/mal-lang/mal-toolbox", rev = "b96258bad474282b975245d9848f7c25d195d508" }
