//! Phase C6 (`PORTING_NOTES.md` §7, §11): the Rust scenario loader must
//! resolve every fixture in `tests/testdata/scenarios` to the same shape
//! the Python `Scenario` does.
//!
//! The Python shape is committed as `tests/testdata/scenario_parity.json`
//! (generated by `tests/scenario_parity.py`, kept current by
//! `tests/test_scenario_parity.py`). This test builds the same shape from
//! the Rust `Scenario` and compares, so Rust and Python are checked
//! against one shared oracle without either calling the other.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use malsim_core::scenario::{
    flatten_attacker_settings, flatten_defender_settings, AttackerSettings, DefenderSettings,
    EntryPoints, NodePropertyRule, RuleValue, Scenario,
};
use maltoolbox_attackgraph::{AttackGraph, AttackGraphNodeId};
use maltoolbox_model::Model;
use serde_json::{json, Map, Value};

/// Fixtures where the two loaders are *expected* to disagree, with the
/// Python error type recorded in the golden file. Each is logged in
/// `PORTING_NOTES.md` §12.
const EXPECTED_DIVERGENCES: [(&str, &str); 1] = [
    // Unknown policy names: Python raises `LookupError`, Rust carries the
    // name opaquely (§2.6, §12 C3).
    ("wrong_agent_classes_scenario.yml", "LookupError"),
];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

/// `os.path.relpath(os.path.realpath(path), REPO_ROOT)`.
fn repo_relative(path: &Path) -> Value {
    let real = path.canonicalize().unwrap();
    json!(real.strip_prefix(repo_root()).unwrap().to_string_lossy())
}

struct Ctx<'a> {
    graph: &'a AttackGraph,
    model: &'a Model,
}

impl Ctx<'_> {
    fn name(&self, id: AttackGraphNodeId) -> String {
        self.graph.full_name_of(id, Some(self.model))
    }

    fn sorted_names<'b>(&self, ids: impl IntoIterator<Item = &'b AttackGraphNodeId>) -> Value {
        let mut names: Vec<String> = ids.into_iter().map(|&id| self.name(id)).collect();
        names.sort();
        json!(names)
    }

    fn rule_per_node<T: RuleValue>(&self, rule: Option<&NodePropertyRule<T>>) -> Value {
        match rule {
            None => Value::Null,
            Some(rule) => self.by_name(
                rule.per_node(self.graph, self.model)
                    .into_iter()
                    .map(|(id, v)| (id, v.to_rule_value())),
            ),
        }
    }

    fn by_name(&self, entries: impl IntoIterator<Item = (AttackGraphNodeId, Value)>) -> Value {
        let sorted: BTreeMap<String, Value> = entries
            .into_iter()
            .map(|(id, v)| (self.name(id), v))
            .collect();
        Value::Object(sorted.into_iter().collect())
    }

    fn optional_names<'b>(
        &self,
        ids: Option<impl IntoIterator<Item = &'b AttackGraphNodeId>>,
    ) -> Value {
        ids.map_or(Value::Null, |ids| self.sorted_names(ids))
    }

    fn rate_map(&self, rates: Option<&std::collections::HashMap<AttackGraphNodeId, f64>>) -> Value {
        match rates {
            None => Value::Null,
            Some(rates) => json!({
                "len": rates.len(),
                "nonzero": self.by_name(
                    rates.iter().filter(|(_, r)| **r != 0.0).map(|(&id, &r)| (id, json!(r)))
                ),
            }),
        }
    }

    fn attacker(
        &self,
        settings: &AttackerSettings<AttackGraphNodeId>,
        agent: &mut Map<String, Value>,
    ) {
        let (entry_points, single_set) = match &settings.entry_points {
            EntryPoints::Single(eps) => (self.sorted_names(eps), eps.clone()),
            EntryPoints::Multiple(sets) => (
                Value::Array(sets.iter().map(|eps| self.sorted_names(eps)).collect()),
                Default::default(),
            ),
        };
        agent.insert("entry_points".into(), entry_points);
        agent.insert("goals".into(), self.sorted_names(&settings.goals));
        agent.insert(
            "rewards".into(),
            self.rule_per_node(settings.rewards.as_ref()),
        );
        agent.insert(
            "actionable_steps".into(),
            self.rule_per_node(settings.actionable_steps.as_ref()),
        );
        agent.insert(
            "ttc_dists".into(),
            self.rule_per_node(settings.ttc_dists.as_ref()),
        );

        let flat = flatten_attacker_settings(settings, self.graph, self.model, &single_set);
        agent.insert(
            "flat".into(),
            json!({
                "actionable_steps": self.optional_names(flat.actionable_steps.as_ref()),
                "ttc_dists": flat.ttc_dists.map_or(Value::Null, |dists| {
                    self.by_name(dists.into_iter().map(|(id, d)| (id, d.to_dict())))
                }),
            }),
        );
    }

    fn defender(&self, settings: &DefenderSettings, agent: &mut Map<String, Value>) {
        agent.insert(
            "rewards".into(),
            self.rule_per_node(settings.rewards.as_ref()),
        );
        agent.insert(
            "actionable_steps".into(),
            self.rule_per_node(settings.actionable_steps.as_ref()),
        );
        agent.insert(
            "observable_steps".into(),
            self.rule_per_node(settings.observable_steps.as_ref()),
        );
        agent.insert(
            "false_positive_rates".into(),
            self.rule_per_node(settings.false_positive_rates.as_ref()),
        );
        agent.insert(
            "false_negative_rates".into(),
            self.rule_per_node(settings.false_negative_rates.as_ref()),
        );

        let flat = flatten_defender_settings(settings, self.graph, self.model);
        agent.insert(
            "flat".into(),
            json!({
                "actionable_steps": self.optional_names(flat.actionable_steps.as_ref()),
                "observable_steps": self.optional_names(flat.observable_steps.as_ref()),
                "false_positive_rates": self.rate_map(flat.false_positive_rates.as_ref()),
                "false_negative_rates": self.rate_map(flat.false_negative_rates.as_ref()),
            }),
        );
    }
}

/// Rust counterpart of `tests/scenario_parity.py::scenario_shape`.
fn scenario_shape(scenario: &Scenario) -> Value {
    let graph = scenario.attack_graph.borrow();
    let model = scenario.model.borrow();
    let ctx = Ctx {
        graph: &graph,
        model: &model,
    };

    let mut agents = Vec::new();
    for settings in &scenario.agent_settings {
        let mut agent = Map::new();
        agent.insert("name".into(), json!(settings.name()));
        agent.insert("type".into(), json!(settings.agent_type().value()));
        match settings {
            malsim_core::scenario::AgentSettings::Attacker(a) => {
                agent.insert("policy".into(), json!(a.policy));
                agent.insert("reward_mode".into(), json!(a.reward_mode.name()));
                ctx.attacker(a, &mut agent);
            }
            malsim_core::scenario::AgentSettings::Defender(d) => {
                agent.insert("policy".into(), json!(d.policy));
                agent.insert("reward_mode".into(), json!(d.reward_mode.name()));
                ctx.defender(d, &mut agent);
            }
        }
        agents.push(Value::Object(agent));
    }

    let s = &scenario.sim_settings;
    json!({
        "lang_file": repo_relative(Path::new(&scenario.lang_file)),
        "model_file": scenario.model_file.as_deref().map_or(Value::Null, repo_relative),
        "num_nodes": graph.nodes.len(),
        "sim_settings": {
            "ttc_mode": s.ttc_mode.name(),
            "run_defense_step_bernoullis": s.run_defense_step_bernoullis,
            "run_attack_step_bernoullis": s.run_attack_step_bernoullis,
            "skip_compromised": s.attack_surface.skip_compromised,
            "skip_unnecessary": s.attack_surface.skip_unnecessary,
            "compromise_entrypoints_at_start": s.compromise_entrypoints_at_start,
            "seed": s.seed,
            "uncompromise_untraversable_steps": s.uncompromise_untraversable_steps,
        },
        "agents": agents,
    })
}

/// JSON numbers compare by value: Python writes a YAML `2` as `2`, Rust's
/// `f64` rules as `2.0`.
fn normalize(value: &Value) -> Value {
    match value {
        Value::Number(n) => json!(n.as_f64().unwrap()),
        Value::Array(items) => Value::Array(items.iter().map(normalize).collect()),
        Value::Object(map) => {
            Value::Object(map.iter().map(|(k, v)| (k.clone(), normalize(v))).collect())
        }
        other => other.clone(),
    }
}

/// The JSON path of the first difference, for a readable failure.
fn first_difference(path: &str, expected: &Value, actual: &Value) -> Option<String> {
    match (expected, actual) {
        (Value::Object(e), Value::Object(a)) => {
            for key in e.keys().chain(a.keys().filter(|k| !e.contains_key(*k))) {
                let (ev, av) = (
                    e.get(key).unwrap_or(&Value::Null),
                    a.get(key).unwrap_or(&Value::Null),
                );
                if !e.contains_key(key) || !a.contains_key(key) {
                    return Some(format!(
                        "{path}.{key}: python={ev} rust={av} (key missing on one side)"
                    ));
                }
                if let Some(diff) = first_difference(&format!("{path}.{key}"), ev, av) {
                    return Some(diff);
                }
            }
            None
        }
        (Value::Array(e), Value::Array(a)) if e.len() == a.len() => e
            .iter()
            .zip(a)
            .enumerate()
            .find_map(|(i, (ev, av))| first_difference(&format!("{path}[{i}]"), ev, av)),
        _ if expected == actual => None,
        _ => Some(format!("{path}: python={expected} rust={actual}")),
    }
}

#[test]
fn rust_scenario_loader_matches_python_golden_shapes() {
    let root = repo_root();
    let golden: Map<String, Value> = serde_json::from_str(
        &std::fs::read_to_string(root.join("tests/testdata/scenario_parity.json")).unwrap(),
    )
    .unwrap();
    assert!(golden.len() > 30, "golden file looks truncated");

    let scenarios_dir = root.join("tests/testdata/scenarios");
    let mut failures = Vec::new();
    for (fixture, expected) in &golden {
        let loaded = Scenario::load_from_file(scenarios_dir.join(fixture));
        let divergence = EXPECTED_DIVERGENCES.iter().find(|(f, _)| f == fixture);

        match (expected.get("error"), loaded) {
            (Some(error), result) => match divergence {
                Some((_, python_error)) => {
                    assert_eq!(error, python_error, "{fixture}: divergence entry is stale");
                    if let Err(e) = result {
                        failures.push(format!(
                            "{fixture}: expected Rust to load it (known divergence), got {e}"
                        ));
                    }
                }
                None => {
                    if result.is_ok() {
                        failures.push(format!("{fixture}: Python raises {error}, Rust loaded it"));
                    }
                }
            },
            (None, Err(e)) => {
                failures.push(format!("{fixture}: Python loads it, Rust failed: {e}"))
            }
            (None, Ok(scenario)) => {
                assert!(
                    divergence.is_none(),
                    "{fixture}: listed as divergence but Python loads it"
                );
                let actual = normalize(&scenario_shape(&scenario));
                if let Some(diff) = first_difference(fixture, &normalize(expected), &actual) {
                    failures.push(diff);
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} fixture(s) differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
