[package]
name = "malsim-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
maltoolbox-attackgraph = { workspace = true }
rand = "0.10.3"
serde_json = "1.0.151"
statrs = { version = "0.19.1", default-features = false, features = ["std", "rand"] }

[dev-dependencies]
maltoolbox-language = { workspace = true }
